# Generated by Django 5.1.4 on 2025-01-05 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseApp', '0002_alter_items_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='Item_name',
            field=models.CharField(max_length=30),
        ),
    ]
