# Generated by Django 5.1.4 on 2025-01-05 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BaseApp', '0003_alter_items_item_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='rating',
            new_name='Rating',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='username',
            new_name='Username',
        ),
    ]
